"""admin control: hours, options, coupons, media, delivery

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 22:45:18.319528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('PERCENT', 'FIXED', name='couponkind', native_enum=False, length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value > 0', name='chk_coupons_value'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_coupons_tenant_code')
    )
    op.create_index(op.f('ix_coupons_tenant_id'), 'coupons', ['tenant_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_categories_tenant_id', 'categories', ['tenant_id', 'id'])
    op.add_column('customers', sa.Column('phone_digits', sa.String(length=15), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    # Backfill normalized phones (digits only, no country code); duplicates keep only the oldest row.
    op.execute("""
        WITH normalized AS (
            SELECT id, tenant_id,
                   CASE WHEN d ~ '^55[0-9]{10,11}$' THEN substr(d, 3) ELSE d END AS digits,
                   created_at
            FROM (SELECT id, tenant_id, created_at, regexp_replace(coalesce(phone, ''), '\\D', '', 'g') AS d FROM customers) raw
        ), ranked AS (
            SELECT id, digits,
                   row_number() OVER (PARTITION BY tenant_id, digits ORDER BY created_at, id) AS position
            FROM normalized WHERE digits <> ''
        )
        UPDATE customers c SET phone_digits = ranked.digits FROM ranked WHERE c.id = ranked.id AND ranked.position = 1
    """)
    op.drop_index(op.f('idx_customers_tenant_phone'), table_name='customers')
    op.create_unique_constraint('uq_customers_tenant_id', 'customers', ['tenant_id', 'id'])
    op.create_index('uq_customers_tenant_phone_digits', 'customers', ['tenant_id', 'phone_digits'], unique=True, postgresql_where=sa.text('phone_digits IS NOT NULL'))
    op.add_column('order_items', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=300), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('service_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.drop_constraint(op.f('fk_orders_customer'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_tenant_customer', 'orders', 'customers', ['tenant_id', 'customer_id'], ['tenant_id', 'id'])
    op.add_column('products', sa.Column('available', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('products', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_unique_constraint('uq_products_tenant_id', 'products', ['tenant_id', 'id'])
    op.drop_constraint(op.f('fk_products_category'), 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_tenant_category', 'products', 'categories', ['tenant_id', 'category_id'], ['tenant_id', 'id'])
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('instagram', sa.String(length=60), nullable=True))
    op.add_column('tenants', sa.Column('cover_url', sa.String(length=300), nullable=True))
    op.add_column('tenants', sa.Column('pix_key', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('hours_mode', sa.String(length=10), server_default='MANUAL', nullable=False))
    op.add_column('tenants', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('tenants', sa.Column('enabled_services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["DINE_IN","TAKEAWAY"]\'::jsonb'), nullable=False))
    op.add_column('tenants', sa.Column('accepted_payments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["CASH","PIX","CARD"]\'::jsonb'), nullable=False))
    op.add_column('tenants', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('service_fee_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'service_fee_percent')
    op.drop_column('tenants', 'min_order_value')
    op.drop_column('tenants', 'delivery_fee')
    op.drop_column('tenants', 'accepted_payments')
    op.drop_column('tenants', 'enabled_services')
    op.drop_column('tenants', 'opening_hours')
    op.drop_column('tenants', 'hours_mode')
    op.drop_column('tenants', 'pix_key')
    op.drop_column('tenants', 'cover_url')
    op.drop_column('tenants', 'instagram')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'description')
    op.drop_constraint('fk_products_tenant_category', 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_category'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint('uq_products_tenant_id', 'products', type_='unique')
    op.drop_column('products', 'options')
    op.drop_column('products', 'sort_order')
    op.drop_column('products', 'available')
    op.drop_constraint('fk_orders_tenant_customer', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_customer'), 'orders', 'customers', ['customer_id'], ['id'])
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'service_fee')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('order_items', 'options')
    op.drop_index('uq_customers_tenant_phone_digits', table_name='customers', postgresql_where=sa.text('phone_digits IS NOT NULL'))
    op.drop_constraint('uq_customers_tenant_id', 'customers', type_='unique')
    op.create_index(op.f('idx_customers_tenant_phone'), 'customers', ['tenant_id', 'phone'], unique=False)
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'phone_digits')
    op.drop_constraint('uq_categories_tenant_id', 'categories', type_='unique')
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_coupons_tenant_id'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
